require('dotenv').config();

const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { URL } = require('url');
const { createClient } = require('@supabase/supabase-js');

const ROOT = __dirname;
const originalCreateServer = http.createServer.bind(http);
const supabaseUrl = process.env.SUPABASE_URL;
const serviceKey = process.env.SUPABASE_SECRET_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;
const db = supabaseUrl && serviceKey ? createClient(supabaseUrl, serviceKey, { auth: { persistSession: false, autoRefreshToken: false } }) : null;
const clean = (v, n = 4000) => String(v ?? '').trim().slice(0, n);
const normalizePhone = v => String(v || '').replace(/\D/g, '').slice(-10);
const xml = (res, status, body = '<Response></Response>') => { res.writeHead(status, { 'Content-Type': 'text/xml; charset=utf-8', 'Content-Length': Buffer.byteLength(body), 'Cache-Control': 'no-store' }); res.end(body); };
const json = (res, status, body) => { const text = JSON.stringify(body); res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': Buffer.byteLength(text), 'Cache-Control': 'no-store' }); res.end(text); };
function readRaw(req, limit = 1024 * 1024) { return new Promise((resolve, reject) => { let raw = ''; req.on('data', chunk => { raw += chunk; if (raw.length > limit) { reject(new Error('Payload too large')); req.destroy(); } }); req.on('end', () => resolve(raw)); req.on('error', reject); }); }
function parseCookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim().split('=')).filter(x=>x[0]).map(([k,...v])=>[k,decodeURIComponent(v.join('='))]));}
function publicRequestUrl(req) { const proto = String(req.headers['x-forwarded-proto'] || 'https').split(',')[0].trim(); const host = String(req.headers['x-forwarded-host'] || req.headers.host || '').split(',')[0].trim(); return `${proto}://${host}${req.url}`; }
function validTwilioSignature(req, params) { const token = process.env.TWILIO_AUTH_TOKEN; const signature = String(req.headers['x-twilio-signature'] || ''); if (!token || !signature) return false; let payload = publicRequestUrl(req); for (const key of Object.keys(params).sort()) payload += key + params[key]; const expected = crypto.createHmac('sha1', token).update(payload).digest('base64'); const a = Buffer.from(signature), b = Buffer.from(expected); return a.length === b.length && crypto.timingSafeEqual(a, b); }
async function findLeadByPhone(phone) { if (!db) return null; const target = normalizePhone(phone); if (!target) return null; const { data, error } = await db.from('leads').select('*').order('updated_at', { ascending: false }).limit(2000); if (error) throw error; return (data || []).find(l => normalizePhone(l.phone) === target) || null; }
async function recordInboundSms(params) { const from = clean(params.From, 80), to = clean(params.To, 80), text = clean(params.Body, 4000); if (!from || !text) return { matched: false }; if (process.env.TWILIO_FROM && normalizePhone(to) !== normalizePhone(process.env.TWILIO_FROM)) return { matched: false }; const lead = await findLeadByPhone(from); if (!lead) return { matched: false }; let { data: conversation, error: convError } = await db.from('conversations').select('*').eq('workspace_id', lead.workspace_id).eq('lead_id', lead.id).maybeSingle(); if (convError) throw convError; if (!conversation) { const created = await db.from('conversations').insert({ workspace_id: lead.workspace_id, lead_id: lead.id, name: lead.name, mode: 'human', unread: 0 }).select('*').single(); if (created.error) throw created.error; conversation = created.data; } const inserted = await db.from('messages').insert({ workspace_id: lead.workspace_id, conversation_id: conversation.id, sender: 'customer', text }); if (inserted.error) throw inserted.error; const nextUnread = Math.max(0, Number(conversation.unread) || 0) + 1; const updated = await db.from('conversations').update({ unread: nextUnread, updated_at: new Date().toISOString(), mode: 'human', name: lead.name }).eq('id', conversation.id).eq('workspace_id', lead.workspace_id); if (updated.error) throw updated.error; await db.from('activities').insert({ workspace_id: lead.workspace_id, type: 'message', title: 'Customer text message', detail: `${lead.name} · ${text.slice(0, 80)}` }); return { matched: true, leadId: lead.id, conversationId: conversation.id }; }
async function authProfile(req){if(!db)return null;const token=parseCookies(req).sr_access;if(!token)return null;const got=await db.auth.getUser(token);const user=got.data?.user;if(!user)return null;const profile=(await db.from('profiles').select('*').eq('id',user.id).maybeSingle()).data;return profile?{user,profile}:null;}
async function ownerEmail(){if(process.env.SITEREMADE_UPDATES_EMAIL)return process.env.SITEREMADE_UPDATES_EMAIL;if(!db)return '';const owner=(await db.from('profiles').select('id').eq('role','owner').limit(1).maybeSingle()).data;if(!owner?.id)return '';const got=await db.auth.admin.getUserById(owner.id);return got.data?.user?.email||'';}
async function sendWebsiteUpdateEmail(updateId,eventName){if(!db||!process.env.RESEND_API_KEY||!updateId)return;try{const row=(await db.from('website_updates').select('*').eq('id',updateId).maybeSingle()).data;if(!row)return;const ws=(await db.from('workspaces').select('business_name,email').eq('id',row.workspace_id).maybeSingle()).data;const to=await ownerEmail();if(!to)return;const subject=`SiteRemade website request — ${ws?.business_name||'Client'}`;const lines=[`Business: ${ws?.business_name||'Client'}`,`Page: ${row.page}`,`Priority: ${row.priority}`,`Status: ${row.status}`,`Request: ${row.request}`,row.notes?`Notes: ${row.notes}`:'',`Event: ${eventName}`].filter(Boolean);await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.RESEND_FROM||'SiteRemade <hello@siteremade.com>',to:[to],subject,text:lines.join('\n')})});}catch(e){console.error('Website update email:',e.message);}}
async function adminOverview(req,res){const a=await authProfile(req);if(!a||a.profile.role!=='owner')return json(res,403,{ok:false,message:'Owner only.'});const [workspaces,leads,conversations,updates]=await Promise.all([db.from('workspaces').select('id,business_name,email,siteremade_subscription_status'),db.from('leads').select('workspace_id,status'),db.from('conversations').select('workspace_id,unread'),db.from('website_updates').select('*').order('created_at',{ascending:false}).limit(100)]);for(const r of [workspaces,leads,conversations,updates])if(r.error)throw r.error;const ws=(workspaces.data||[]).map(w=>({id:w.id,businessName:w.business_name,email:w.email,status:w.siteremade_subscription_status||'inactive',activeLeads:(leads.data||[]).filter(l=>l.workspace_id===w.id&&!['Won','Lost'].includes(l.status)).length,unread:(conversations.data||[]).filter(c=>c.workspace_id===w.id).reduce((n,c)=>n+Math.max(0,Number(c.unread)||0),0)}));const names=new Map(ws.map(w=>[w.id,w.businessName]));return json(res,200,{ok:true,workspaces:ws,updateRequests:(updates.data||[]).map(r=>({id:r.id,workspaceId:r.workspace_id,businessName:names.get(r.workspace_id)||'Client',page:r.page,priority:r.priority,request:r.request,status:r.status,createdAt:r.created_at}))});}
function enhancedHtml(filename) { let html = fs.readFileSync(path.join(ROOT, filename), 'utf8'); if (!html.includes('/v17.css')) html = html.replace('</head>', '  <link rel="stylesheet" href="/v17.css?v=17" />\n</head>'); if (!html.includes('/v18.css')) html = html.replace('</head>', '  <link rel="stylesheet" href="/v18.css?v=18" />\n</head>'); if (!html.includes('/v19.css')) html = html.replace('</head>', '  <link rel="stylesheet" href="/v19.css?v=19" />\n</head>'); if (!html.includes('/v17-client.js')) html = html.replace('</body>', '  <script src="/v17-client.js?v=17"></script>\n</body>'); if (!html.includes('/v18-client.js')) html = html.replace('</body>', '  <script src="/v18-client.js?v=18"></script>\n</body>'); if (!html.includes('/v19-client.js')) html = html.replace('</body>', '  <script src="/v19-client.js?v=19"></script>\n</body>'); return html; }
http.createServer = function patchedCreateServer(listener) { return originalCreateServer(async (req, res) => { try { const u = new URL(req.url, `http://${req.headers.host || 'localhost'}`); if (req.method === 'GET' && (u.pathname === '/' || u.pathname === '/index.html' || u.pathname === '/app.html')) { const file = u.pathname === '/app.html' ? 'app.html' : 'index.html'; const body = enhancedHtml(file); res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': Buffer.byteLength(body), 'Cache-Control': 'no-store' }); return res.end(body); } if (req.method === 'POST' && u.pathname === '/api/public/twilio/inbound') { if (!db) return xml(res, 503); const raw = await readRaw(req); const params = Object.fromEntries(new URLSearchParams(raw)); if (!validTwilioSignature(req, params)) return xml(res, 403); await recordInboundSms(params); return xml(res, 200); } if(req.method==='GET'&&u.pathname==='/api/v19/admin/overview')return await adminOverview(req,res);const watch=(req.method==='POST'&&u.pathname==='/api/app/website-updates')||(req.method==='PATCH'&&u.pathname.startsWith('/api/app/website-updates/'));if(watch){const end=res.end.bind(res);res.end=(chunk,...args)=>{end(chunk,...args);if(res.statusCode>=200&&res.statusCode<300){try{const payload=JSON.parse(Buffer.isBuffer(chunk)?chunk.toString('utf8'):String(chunk||''));const id=payload.websiteUpdate?.id;if(id)setImmediate(()=>sendWebsiteUpdateEmail(id,req.method==='POST'?'New request':'Status changed'));}catch{}}};}return listener(req, res); } catch (error) { console.error('V19 middleware:', error); if (!res.headersSent) return json(res, 500, { ok: false, message: 'Server error' }); res.end(); } }); };
