document.documentElement.dataset.siteremadeVersion='19';
(() => {
  const byId=id=>document.getElementById(id);
  const make=(tag,cls,text)=>{const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el;};
  const activeLead=l=>!['Won','Lost'].includes(l.status);
  const daysOld=iso=>Math.max(0,Math.floor((Date.now()-new Date(iso||Date.now()).getTime())/86400000));
  const leadConversation=l=>state.conversations.find(c=>c.leadId===l.id&&Array.isArray(c.messages)&&c.messages.length);
  const waitingReply=l=>{const c=leadConversation(l);const m=c?.messages?.[c.messages.length-1];return m?.from==='customer';};
  function addStat(parent,label,value,view){const b=make('button','v19-focus-card');b.dataset.view=view;b.append(make('span','',label),make('strong','',String(value)));b.addEventListener('click',()=>switchView(view));parent.appendChild(b);}
  function ensureFocus(){const home=byId('view-home');if(!home||byId('v19FocusStrip'))return;const strip=make('div','v19-focus-strip');strip.id='v19FocusStrip';const head=home.querySelector('.page-head');if(head)head.insertAdjacentElement('afterend',strip);}
  function renderFocus(){ensureFocus();const strip=byId('v19FocusStrip');if(!strip)return;strip.replaceChildren();const active=state.leads.filter(activeLead).length;const unread=state.conversations.reduce((n,c)=>n+Math.max(0,Number(c.unread)||0),0);const stale=state.leads.filter(l=>activeLead(l)&&daysOld(l.updatedAt||l.createdAt)>=2).length;const today=new Date().toDateString();const booked=state.appointments.filter(a=>new Date(a.start).toDateString()===today).length;const pending=state.invoices.filter(i=>i.status==='Pending').reduce((n,i)=>n+Number(i.amount||0),0);addStat(strip,'ACTIVE LEADS',active,'leads');addStat(strip,'WAITING REPLIES',unread,'inbox');addStat(strip,'FOLLOW UPS',stale,'leads');addStat(strip,"TODAY'S BOOKINGS",booked,'calendar');addStat(strip,'OUTSTANDING',money(pending),'payments');}
  function ensureSetup(){if(state.user?.role==='owner')return null;const home=byId('view-home'),head=home?.querySelector('.page-head');if(!head)return null;let box=byId('v19Setup');if(!box){box=make('section','v19-setup');box.id='v19Setup';head.insertAdjacentElement('afterend',box);}return box;}
  function renderSetup(){const box=ensureSetup();if(!box)return;const rows=[['Business details',!!(state.workspace.businessName&&state.workspace.email),'settings'],['Phone number',!!state.workspace.phone,'settings'],['Services',!!state.workspace.ai?.services,'settings'],['Service area',!!state.workspace.ai?.serviceArea,'settings'],['Find customers',state.prospectViews?.length>0||state.leads.length>0,'prospecting'],['Work the pipeline',state.leads.length>0,'leads']];const done=rows.filter(r=>r[1]).length,pct=Math.round(done/rows.length*100);box.hidden=pct===100;box.replaceChildren();const copy=make('div','v19-setup-copy');copy.append(make('p','eyebrow','WORKSPACE SETUP'),make('strong','',`${pct}% ready to convert leads`),make('span','', 'Finish the essentials so SiteRemade can work around your business.'));const track=make('div','v19-setup-track');const fill=make('i');fill.style.width=`${pct}%`;track.appendChild(fill);const steps=make('div','v19-setup-steps');rows.forEach(([name,ok,view])=>{const b=make('button',ok?'done':'',`${ok?'✓':'○'} ${name}`);b.addEventListener('click',()=>switchView(view));steps.appendChild(b)});box.append(copy,track,steps);}
  function ensurePipeline(){const toolbar=byId('view-leads')?.querySelector('.lead-toolbar');if(!toolbar)return null;let el=byId('v19Pipeline');if(!el){el=make('section','v19-pipeline');el.id='v19Pipeline';toolbar.insertAdjacentElement('beforebegin',el);}return el;}
  function renderPipeline(){const el=ensurePipeline();if(!el)return;el.replaceChildren();const head=make('div','v19-pipeline-head');const left=make('div');left.append(make('p','eyebrow','CONVERSION PIPELINE'),make('strong','',`${state.leads.filter(activeLead).length} active opportunities`));const won=state.leads.filter(l=>l.status==='Won').length,closed=state.leads.filter(l=>['Won','Lost'].includes(l.status)).length;head.append(left,make('span','',`${closed?Math.round(won/closed*100):0}% close rate`));const cols=make('div','v19-pipeline-cols');['New','Contacted','Quoted','Won','Lost'].forEach(status=>{const rows=state.leads.filter(l=>l.status===status),value=rows.reduce((n,l)=>n+(Number(l.value)||0),0);const b=make('button');b.append(make('span','',status),make('strong','',String(rows.length)),make('small','',value?money(value):'—'));b.addEventListener('click',()=>{state.filter=status;qsa('#leadFilters button').forEach(x=>x.classList.toggle('active',x.dataset.status===status));renderLeads();});cols.appendChild(b)});el.append(head,cols);}
  function nextAction(l){if(waitingReply(l))return['Reply now','inbox'];if(l.status==='New')return['Contact lead','lead'];if(l.status==='Contacted')return['Follow up','lead'];if(l.status==='Quoted')return['Follow up quote','lead'];return['Open lead','lead'];}
  function openNext(l,kind){if(kind==='inbox'){const c=leadConversation(l);if(c){state.selectedConversationId=c.id;switchView('inbox');renderInbox();return;}}openLead(l.id);}
  function upgradeLeadRows(){document.querySelectorAll('#leadTableBody tr[data-id]').forEach(row=>{const l=state.leads.find(x=>x.id===row.dataset.id);if(!l)return;let cell=row.querySelector('.v19-next-cell');if(!cell){cell=make('td','v19-next-cell');row.insertBefore(cell,row.lastElementChild);}cell.replaceChildren();const [label,kind]=nextAction(l);const b=make('button','v19-next-button',label);b.addEventListener('click',e=>{e.stopPropagation();openNext(l,kind)});cell.appendChild(b)});const tr=document.querySelector('.lead-table thead tr');if(tr&&!tr.querySelector('.v19-next-head')){const th=make('th','v19-next-head','Next action');tr.insertBefore(th,tr.lastElementChild);}}
  function ensureFinderPresets(){const form=byId('prospectingForm');if(!form||byId('v19FinderPresets'))return;const box=make('div','v19-finder-presets');box.id='v19FinderPresets';box.appendChild(make('span','','Quick targeting'));const presets=[['Best local prospects','best'],['No website + phone','noweb'],['Established','established'],['Referral partners','partners']];const set=(n,v)=>{if(form.elements[n])form.elements[n].value=v};presets.forEach(([label,key])=>{const b=make('button','',label);b.type='button';b.addEventListener('click',()=>{if(key==='best'){set('purpose','prospects');set('minRating','4');set('minReviews','10');set('maxReviews','150');set('website','any');set('phone','yes')}if(key==='noweb'){set('purpose','prospects');set('minRating','4');set('minReviews','5');set('maxReviews','200');set('website','no');set('phone','yes')}if(key==='established'){set('purpose','prospects');set('minRating','4.5');set('minReviews','25');set('maxReviews','300');set('website','any');set('phone','yes')}if(key==='partners'){set('purpose','partners');set('minRating','4');set('minReviews','10');set('website','yes');set('phone','yes')}if(form.elements.newOnly)form.elements.newOnly.checked=true;});box.appendChild(b)});form.insertBefore(box,form.firstElementChild);}
  function scoreProspects(){document.querySelectorAll('.prospect-card').forEach((card,i)=>{const p=state.prospects[i];if(!p)return;let fit=35;if(p.phone)fit+=20;if(!p.website)fit+=15;else fit+=5;if(Number(p.rating)>=4.3)fit+=12;if(Number(p.reviews)>=10)fit+=10;if(Number(p.reviews)<=200)fit+=8;fit=Math.min(100,fit);let badge=card.querySelector('.v19-fit');if(!badge){badge=make('span','v19-fit');card.querySelector('.prospect-title-row')?.appendChild(badge);}badge.textContent=`FIT ${fit}`;});}
  function renderDrawerJourney(l){const form=byId('leadDetailForm');if(!form||!l)return;let panel=form.querySelector('.v19-customer-panel');if(!panel){panel=make('section','v19-customer-panel');form.appendChild(panel);}panel.replaceChildren();const c=leadConversation(l),msgs=c?.messages||[],apps=state.appointments.filter(a=>a.leadId===l.id),invs=state.invoices.filter(i=>i.leadId===l.id),pending=invs.filter(i=>i.status==='Pending').reduce((n,i)=>n+Number(i.amount||0),0);const [action]=nextAction(l);const summary=make('div','v19-customer-summary');const copy=make('div');copy.append(make('p','eyebrow','NEXT BEST ACTION'),make('strong','',action),make('span','',`Last activity ${relative(l.updatedAt||l.createdAt)}`));const stats=make('div','v19-customer-stats');[['messages',msgs.length],['bookings',apps.length],['outstanding',money(pending)]].forEach(([name,val])=>{const s=make('span');s.append(make('b','',String(val)),document.createTextNode(` ${name}`));stats.appendChild(s)});summary.append(copy,stats);const journey=make('div','v19-journey');journey.appendChild(make('p','eyebrow','CUSTOMER JOURNEY'));const events=[{t:l.createdAt,n:'Lead created',d:`${l.source||'Unknown source'} · ${l.service||'Inquiry'}`},...msgs.map(m=>({t:m.createdAt,n:m.from==='customer'?'Customer message':m.from==='business'?'Business reply':'AI reply',d:m.text})),...apps.map(a=>({t:a.start,n:'Appointment',d:`${a.title||'Appointment'} · ${a.status||'Booked'}`})),...invs.map(i=>({t:i.createdAt,n:`Invoice ${i.status}`,d:`${i.description} · ${money(i.amount)}`}))].sort((a,b)=>new Date(b.t)-new Date(a.t)).slice(0,10);events.forEach(e=>{const row=make('div','v19-journey-row');row.appendChild(make('i'));const sec=make('section');sec.append(make('strong','',e.n),make('span','',e.d||''),make('small','',relative(e.t)));row.appendChild(sec);journey.appendChild(row)});panel.append(summary,journey);}
  function automationHealth(){const list=byId('automationList');if(!list)return;let box=byId('v19AutomationHealth');if(!box){box=make('div','v19-automation-health');box.id='v19AutomationHealth';list.insertAdjacentElement('beforebegin',box);}box.replaceChildren();const on=state.automations.filter(a=>a.enabled).length;const copy=make('div');copy.append(make('p','eyebrow','LIVE AUTOMATION'),make('strong','',`${on} of ${state.automations.length} workflows active`),make('span','', 'Lead confirmations, business alerts and appointment reminders run automatically when enabled.'));box.append(copy,make('span','status-pill',on?'ACTIVE':'OFF'));}
  function renderAllV19(){renderSetup();renderFocus();renderPipeline();upgradeLeadRows();ensureFinderPresets();scoreProspects();automationHealth();if(state.selectedLeadId){const l=state.leads.find(x=>x.id===state.selectedLeadId);if(l)renderDrawerJourney(l)}}
  function install(){if(!wait())return setTimeout(install,100);const oldAll=renderAll;renderAll=function(){const r=oldAll();renderAllV19();return r;};const oldLeads=renderLeads;renderLeads=function(){const r=oldLeads();renderPipeline();upgradeLeadRows();return r;};const oldProspects=renderProspects;renderProspects=function(){const r=oldProspects();scoreProspects();return r;};const oldDrawer=populateDrawer;populateDrawer=function(l){const r=oldDrawer(l);renderDrawerJourney(l);return r;};const oldAutos=renderAutomations;renderAutomations=function(){const r=oldAutos();automationHealth();return r;};renderAllV19();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
