document.documentElement.dataset.trafficVersion='20';
(() => {
  const ready=()=>typeof state!=='undefined'&&typeof qs==='function'&&typeof renderWebsiteTraffic==='function';
  function trackerUrl(){return `${location.origin}/siteremade-analytics.js?workspace=${encodeURIComponent(state.workspace.id||'')}&key=${encodeURIComponent(state.workspace.publicKey||'')}`;}
  function trackerSnippet(){return '<scr'+'ipt async src="'+trackerUrl()+'"></scr'+'ipt>';}
  function ensure(){const panel=document.querySelector('.traffic-panel');if(!panel||document.querySelector('#v20TrafficSetup'))return;const p=panel.querySelector('.panel-head p');if(p)p.textContent='Real visits tracked directly by SiteRemade. No Google Analytics account required.';const form=document.querySelector('#websiteTrafficForm');if(!form)return;const box=document.createElement('div');box.id='v20TrafficSetup';box.className='v20-traffic-setup';box.innerHTML='<div><p class="eyebrow">LIVE TRACKING</p><strong>Connect the website once</strong><span>Real sessions, visitors and pageviews will appear here.</span></div><div class="v20-tracker-actions"><button type="button" class="secondary-button" id="v20CopyTracker">Copy tracking code</button><span id="v20TrackerState">Ready</span></div><code id="v20TrackerCode"></code>';form.insertAdjacentElement('afterend',box);const note=panel.querySelector('.traffic-note');if(note)note.textContent='Tracking begins after the SiteRemade tracking code is installed on the client website. Counts are first-party visits, not estimates.';document.querySelector('#v20CopyTracker').onclick=async()=>{const code=trackerSnippet();document.querySelector('#v20TrackerCode').textContent=code;try{await navigator.clipboard.writeText(code);document.querySelector('#v20TrackerState').textContent='Copied — install on the website';}catch{document.querySelector('#v20TrackerState').textContent='Copy the code below';}};}
  function render(){ensure();const a=state.websiteAnalytics||{},code=document.querySelector('#v20TrackerCode'),label=document.querySelector('#v20TrackerState'),status=document.querySelector('#trafficConnectionStatus');if(code)code.textContent=trackerSnippet();if(label)label.textContent=a.connected?'Live tracking connected':a.domain?'Domain saved — install tracker':'Save the business domain';if(status){status.textContent=a.connected?'LIVE TRACKING':a.domain?'INSTALL TRACKER':'ADD WEBSITE DOMAIN';status.classList.toggle('neutral',!a.connected);}}
  function install(){if(!ready())return setTimeout(install,80);const old=renderWebsiteTraffic;renderWebsiteTraffic=function(){const r=old();render();return r;};render();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
