document.documentElement.dataset.siteremadeVersion='22';
(() => {
  const wait=()=>typeof state!=='undefined'&&typeof qs==='function'&&typeof renderAll==='function';
  const moneySafe=n=>typeof money==='function'?money(n):`$${Math.round(Number(n)||0).toLocaleString()}`;
  function make(tag,cls,text){const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el;}
  function addHero(viewId,id,kicker,title,copy){const view=qs(viewId),head=view?.querySelector('.page-head');if(!view||!head)return null;let box=qs('#'+id);if(!box){box=make('section','v22-hero');box.id=id;head.insertAdjacentElement('afterend',box);}box.innerHTML=`<div class="v22-hero-copy"><p class="eyebrow">${kicker}</p><h2>${title}</h2><p>${copy}</p></div><div class="v22-hero-stats"></div>`;return box;}
  function renderHomeHero(){const box=addHero('#view-home','v22HomeHero','TODAY\'S BUSINESS','Know exactly what to do next.','SiteRemade pulls your leads, replies, bookings and money into one operating view.');if(!box)return;const active=state.leads.filter(l=>!['Won','Lost'].includes(l.status)).length;const waiting=state.conversations.reduce((n,c)=>n+Math.max(0,Number(c.unread)||0),0);const upcoming=state.appointments.filter(a=>new Date(a.start)>=new Date()).length;const pending=state.invoices.filter(i=>i.status==='Pending').reduce((n,i)=>n+Number(i.amount||0),0);const s=box.querySelector('.v22-hero-stats');[['Active leads',active,'leads'],['Waiting replies',waiting,'inbox'],['Upcoming',upcoming,'calendar'],['Outstanding',moneySafe(pending),'payments']].forEach(([label,val,view])=>{const b=make('button','v22-hero-stat');b.innerHTML=`<span>${label}</span><strong>${val}</strong>`;b.onclick=()=>switchView(view);s.appendChild(b);});}
  function renderAnalyticsHero(){const box=addHero('#view-analytics','v22AnalyticsHero','GROWTH OVERVIEW','From traffic to revenue.','See whether your website is bringing people in and whether your pipeline is turning them into booked work.');if(!box)return;const won=state.leads.filter(l=>l.status==='Won').length,closed=state.leads.filter(l=>['Won','Lost'].includes(l.status)).length,rate=closed?Math.round(won/closed*100):0,traffic=state.websiteAnalytics||{},paid=state.invoices.filter(i=>i.status==='Paid').reduce((n,i)=>n+Number(i.amount||0),0);const s=box.querySelector('.v22-hero-stats');[['Win rate',`${rate}%`],['Website sessions',traffic.connected?Number(traffic.sessions||0).toLocaleString('en-CA'):'Setup'],['Pageviews',traffic.connected?Number(traffic.pageviews||0).toLocaleString('en-CA'):'—'],['Collected',moneySafe(paid)]].forEach(([label,val])=>{const d=make('div','v22-hero-stat');d.innerHTML=`<span>${label}</span><strong>${val}</strong>`;s.appendChild(d);});}
  function polishAnalytics(){const view=qs('#view-analytics');if(!view)return;const traffic=view.querySelector('.traffic-panel');const metrics=view.querySelector('.analytics-metrics');if(traffic&&metrics&&traffic.previousElementSibling!==metrics){metrics.insertAdjacentElement('afterend',traffic);}const ad=view.querySelector('.ads-panel');if(ad)ad.classList.add('v22-secondary-feature');}
  function polishNav(){const inbox=qs('[data-view="inbox"] strong');if(inbox)inbox.textContent='Messages';const home=qs('[data-view="home"] strong');if(home)home.textContent='Overview';const trafficStatus=qs('#trafficConnectionStatus');if(trafficStatus&&trafficStatus.textContent==='INSTALL TRACKER')trafficStatus.textContent='SETUP PENDING';}
  function renderV22(){renderHomeHero();renderAnalyticsHero();polishAnalytics();polishNav();}
  function install(){if(!wait())return setTimeout(install,80);const old=renderAll;renderAll=function(){const r=old();renderV22();return r;};renderV22();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
