(()=>{
let installed=false,twilioStatus=null;
const $=s=>document.querySelector(s);
async function getJson(url,opts={}){const r=await fetch(url,{credentials:'same-origin',...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)throw Error(j.message||'Request failed');return j}
function providerState(id){const button=document.querySelector(`[data-v34="${id}"]`),card=button?.closest('.v34-card'),state=card?.querySelector('.v34-state')?.textContent?.trim()||'',label=card?.querySelector('.v34-label')?.textContent?.trim()||'';return{button,connected:state==='Connected',label}}
async function loadTwilioStatus(){try{twilioStatus=await getJson('/api/app/integrations/twilio/status')}catch{twilioStatus={configured:false,connected:false}}return twilioStatus}
function selectedLead(){const c=state?.conversations?.find(x=>x.id===state.selectedConversationId);return c?state.leads.find(l=>l.id===c.leadId):null}
async function textCustomer(lead){if(!lead?.phone)return alert('This customer does not have a phone number.');const s=twilioStatus||await loadTwilioStatus();if(!s.connected)return alert('Connect your business number before sending texts.');const text=prompt(`Message ${lead.name||lead.phone}:`,'');if(!text?.trim())return;if(!confirm(`Send this message to ${lead.name||lead.phone}?`))return;try{const r=await getJson('/api/app/integrations/twilio/send',{method:'POST',body:JSON.stringify({leadId:lead.id,text:text.trim(),confirmSend:true})});if(typeof refreshLight==='function')await refreshLight();if(r.conversationId)state.selectedConversationId=r.conversationId;if(typeof renderInbox==='function')renderInbox();alert('Message sent.')}catch(e){alert(e.message)}}
function decorateCalendar(){const head=$('#view-calendar .page-head');if(!head)return;let wrap=$('#v38CalendarStatus');if(!wrap){wrap=document.createElement('div');wrap.id='v38CalendarStatus';wrap.className='head-actions';head.appendChild(wrap)}const c=providerState('google_calendar');wrap.innerHTML=c.connected?'<span class="coming-badge">GOOGLE CALENDAR CONNECTED</span><button class="secondary-button" type="button" id="v38CalendarSync">Sync calendar</button>':'<span class="coming-badge neutral">GOOGLE CALENDAR NOT CONNECTED</span>';const b=$('#v38CalendarSync');if(b)b.onclick=()=>c.button?.click()}
async function decorateInbox(){const s=await loadTwilioStatus();const lead=selectedLead(),panel=$('#v29CustomerPanel'),actions=panel?.querySelector('.v29-panel-actions');const existing=$('#v38TextCustomer');if(existing&&!s.connected)existing.remove();if(s.connected&&lead?.phone&&actions&&!actions.querySelector('#v38TextCustomer')){const b=document.createElement('button');b.id='v38TextCustomer';b.type='button';b.textContent='Text';b.onclick=()=>textCustomer(lead);actions.insertBefore(b,actions.lastElementChild)}}
function decoratePayments(){const view=$('#view-payments');if(!view)return;let box=$('#v38StripeStatus');if(!box){box=document.createElement('div');box.id='v38StripeStatus';box.className='panel';view.querySelector('.payment-metrics')?.insertAdjacentElement('beforebegin',box)}const s=providerState('stripe'),invoices=state?.invoices||[],paid=invoices.filter(i=>i.status==='Paid').length,open=invoices.filter(i=>i.status==='Pending').length;box.innerHTML=`<div class="panel-head"><div><p class="eyebrow">CONNECTED PAYMENTS</p><h2>${s.connected?'Stripe is active across customer payments':'Connect Stripe to activate the full payment workflow'}</h2><p>${s.connected?'Payment links and invoice status stay attached to customer records.':'Payment links work, but connected account status and payouts are not active yet.'}</p></div><span class="status-pill ${s.connected?'':'neutral'}">${s.connected?'ACTIVE':'NOT CONNECTED'}</span></div><div class="ad-metrics"><div><span>PAID INVOICES</span><strong>${paid}</strong></div><div><span>OPEN INVOICES</span><strong>${open}</strong></div><div><span>ACCOUNT</span><strong>${s.connected?'CONNECTED':'—'}</strong></div><div><span>WORKFLOW</span><strong>${s.connected?'LIVE':'—'}</strong></div></div>`}
function refresh(){decorateCalendar();decorateInbox();decoratePayments()}
function patch(){if(typeof renderConversationWindow==='function'){const old=renderConversationWindow;renderConversationWindow=function(){const r=old.apply(this,arguments);setTimeout(decorateInbox,0);return r}}}
function install(){if(installed||typeof state==='undefined')return setTimeout(install,100);installed=true;patch();setTimeout(refresh,500);document.addEventListener('click',e=>{if(e.target.closest('[data-view="calendar"],[data-view="inbox"],[data-view="payments"],[data-view="integrations"]'))setTimeout(refresh,180)})}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',install):install();
})();
